// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_auto_ecole.Models;

namespace Projet_auto_ecole.Migrations
{
    [DbContext(typeof(AutoecoleAppContext))]
    partial class AutoecoleAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projet_auto_ecole.Models.Eleve", b =>
                {
                    b.Property<string>("Cin_Eleve")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_naissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cin_Eleve");

                    b.ToTable("Eleve");
                });

            modelBuilder.Entity("Projet_auto_ecole.Models.Examen", b =>
                {
                    b.Property<int>("Id_Examen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cin_Eleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Examen");

                    b.ToTable("Examen");
                });

            modelBuilder.Entity("Projet_auto_ecole.Models.Moniteur", b =>
                {
                    b.Property<string>("Cin_Moniteur")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_naissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cin_Moniteur");

                    b.ToTable("Moniteur");
                });

            modelBuilder.Entity("Projet_auto_ecole.Models.Paiement", b =>
                {
                    b.Property<int>("Id_Paiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cin_Eleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Montant")
                        .HasColumnType("real");

                    b.HasKey("Id_Paiement");

                    b.ToTable("Paiement");
                });

            modelBuilder.Entity("Projet_auto_ecole.Models.Prix", b =>
                {
                    b.Property<int>("Id_Prix")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date_debut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_fin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Montant")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Prix");

                    b.ToTable("Prix");
                });

            modelBuilder.Entity("Projet_auto_ecole.Models.Seance", b =>
                {
                    b.Property<int>("Id_Seance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cin_Eleve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cin_Moniteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Heure_debut")
                        .HasColumnType("int");

                    b.Property<int>("Heure_fin")
                        .HasColumnType("int");

                    b.Property<string>("Immatriculation_Voiture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Seance");

                    b.ToTable("Seance");
                });

            modelBuilder.Entity("Projet_auto_ecole.Models.Voiture", b =>
                {
                    b.Property<string>("Immatriculation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Marque")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Immatriculation");

                    b.ToTable("Voiture");
                });
#pragma warning restore 612, 618
        }
    }
}
